services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: solaceassignment
    ports:
      - "5432:5432"
    networks:
      - default
networks:
  default:
    driver: bridge
